### ISSUE TITLE
Add sql queries for page views

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#10]
Add queries for following pages: 
- stage details (all media);
- stage management possibilities (filtered by stage - list)
- stage management possibilities (all media);
- inputs (filtered by management possibilities - list);
- inputs (all media);
- vendors (filtered by input - list)
- vendors (filtered by variety - list) 
- vendors (all media)
- abiotic risks (filtered by stage - list);
- abiotic risks (all media)
- diseases (filtered by stage - list);
- diseases (all media)
- pests (filtered by stage - list);
- pests (all media);
- varieties (list);
- varieties (all media);

**Comment by chrismclarke** [comment]
I think the most sensible way to go about things would be to design queries which could then be filtered in the app. E.g. if we can return all pests either with columns for each stage and true/false if they are associated or an additional array containing a list of applicable stages.

This will reduce the number of queries to write/execute and make nice use of angular's pipes/filtering abilities (probably be much faster).

**Comment by dave-mills** [comment]
I've solved this in 2 ways.  You will like method 1.  You may despair at method 2: 

**Method 1:** This is using static queries with results that can be cached.  For example, the 'abiotics' Query pulls in data with the following columns (converted to key-value pairs by your convertToRowFormat() function): 
- abioticos_id;
- file_url;
- ab_nombre;
- ab_desc;
- stageList;
  the stage list is a string, like this:  "2,3,4,5".  This can easily be turned into an array, (which I have done in the pests page, on the develop branch), or handled in whatever way you see fit. 

---

**Method 2:** Contrary to our discussions and agreements yesterday, I went all-in on queries that are not all run at the start of the app. See the dynamic_sql branch for details (I separated it into a new branch because I wanted be able to quickly discard it if it turns out to be totally the wrong direction).  

In that branch, I made a bunch of changes to your query-calling methods in sqlite (going through and commenting it all now, so hopefully it'll be clear-ish what I've done). 

Now, the abiotic, pest and disease pages call a query on page load, using the `this.stage.stage_id` to filter the results.  

The main benefit I see is: 
- We don't have to design a totally new way of storing the data in-app and can just use it from the database we already have.  This was starting to bug me yesterday, as I was struggling to work out a good naming system / structure for the data and coming to the realisation that we basically have to preload the entire database into json or local-app storage.  I sort of felt like we were creating an entirely new database system just to get away from sql. 

The potential down side is: 
- app is more sluggish. (but is it too sluggish? Testing on my 2013 nexus, I noticed maybe a 3/4 second lag between pages, compared with a 1/4 to 1/2 second lag in the version using only cached data, but I haven't tested it on an old, slow, device. (but then, it doesn't work for Android 4.2.2, so we have other issues for older devices...).  It also makes no noticeable difference when running in-browser, which (according to Carlos) is where most of the use will be. 

Sorry for totally going back on what we agreed at the start of the week.  If you reckon that running a query on (most) new page-loads would be too intensive for a typical Android device, we can go back to exporting the database into json and querying that instead.

**Comment by chrismclarke** [comment]
Haha, the main thing is having the queries, from there we can do what we want and operate in multiple ways. There are 2 main benefits I see to caching, being
1. speed - this I haven't done much testing on, I'm wondering how time stacks up if all db requests are done at once, worst (unlikely) case is linearly as all queries go through the same process of opening db, sending query and waiting for result, best (still unlikely) is no extra time needed as all the requests can be run in parallel.
   This is actually a fairly major issue - people expect apps to be responsive and if they are not immediately people tend to assume they have done something wrong, i.e. not tapped correctly (as is easily possible on older devices). If we do end up with a system that is a little bit slow then we will need to throw in a few extra features such as blocking/hiding ui elements that have already been pressed or are waiting on other actions (c.f. start page button), or adding loading animations. Ionic does have a native 'load' module to take care of the second so it's not a huge deal, just something to think about. 
2. compatibility - My cheap crappy device wasn't able to use the sql plugin for whatever reason, still need to test but I'd be surprised if it cant read from a json file. 

I see no reason to not push forward with both and test. Ideally we can make things nice and modular so that any of these methods can easily be swapped in and out

**Comment by chrismclarke** [comment]
I've used your stageList output and cached json data to prepopulate pages with number of results available. You'll noticed that essentially executing all 4 filter functions as the stage info page loads is incredibly quick.

**Comment by dave-mills** [comment]
Very neat!  Will update query cache soon to allow more of this json-magic.

**Comment by dave-mills** [comment]
masterQueries and cached-json updated.  

At present, the lists variables are written for the direction of travel through the app, i.e. diseases has stageList, but stages does not have diseaseList.  

Would it be useful to have all lists in all things that are linked? 

###Edit - my guess is yes, but not immediately.  Closing this comment and moving to 2nd milestone.
