### ISSUE TITLE
Functions into seperate provider

### ISSUE THREAD

**Issue by dave-mills** [dave-mills/proinpa#13]
We'll need updateUrl on every page, and there may be more such global functions.  For speed I copied it into abioticos.ts, but we should probably move it into a new provider.

I'll take a look when I get home, unless you want to swoop in and do this one :-)

**Comment by chrismclarke** [comment]
Agreed, I'll add a globalFunctions service later

**Comment by chrismclarke** [comment]
Service added, however updataeUrl() will need to be modified as it's very specified to the stages page (passing stageIndex and updating this.stages).

Should instead just return de-foreigned strings and bound to in the html.

**Comment by chrismclarke** [comment]
Change of plan, makes more sense to use directives.
Directives are a way to change the behaviour of a dom element, you will have already seen loads of examples, e.g. `<ion-item **item-left**>` - item-left is a directive that takes the element and aligns to the left of the page.

Similarly you can write custom directives that can be imported into a page. I've written one called 'image-fallback' - you can add it into any <img> tag, e.g.`<img image-fallback src="...">` 
The directive changes the default onError function of the image to instead run the special character replacement code and update the src accordingly. 

In order to use this (or any other directives) in a page you must do 2 things:
1. import the directive (currently in a seperate directives folder)
2. include the directive in the component decorator, i.e. @component {templateUrl:'...', directives=[image-fallback]

You can see a full implementation in the main.ts/main.html files.
The image-fallback directive took a lot of work to figure out, in the end I couldn't use the same special character search and had to fallback on regex matching but I think it should still be fairly robust (according to [http://www.utf8-chartable.de/](http://www.utf8-chartable.de/) should be of the form `%[A-Z][0-9]%[A-Z][A-Z0-9]`

Note - the method currently only replaces the first found special character. We don't currently have any examples in the database with more than one special character to test outputs with. Can re-open later if come across.
